platform :ios, '7.0'
pod 'Overcoat', '~> 1.2'
pod 'Foursquare-API-v2', '~> 1.4'
pod 'MDCSwipeToChoose'
pod 'AKLocationManager'
pod 'Underscore.m', '~> 0.2'
pod 'pop', '~> 1.0'
pod 'BlocksKit', '~> 2.2'
pod 'UIImage+AverageColor', '~> 1.0'
pod 'VTAcknowledgementsViewController'
